// sanity/schemas/atlasSeries.js
// Atlas of the Unspoken / Atlas de l'Inexprimé — 2-tome bilingual series

export default {
  name: 'atlasSeries',
  title: 'Atlas — Series Entry',
  type: 'document',
  icon: () => '📚',
  groups: [
    { name:'meta',   title:'📋 Series Meta',  default:true },
    { name:'tome1',  title:'📖 Tome I' },
    { name:'tome2',  title:'📖 Tome II' },
    { name:'retail', title:'🛒 Retail Links' },
    { name:'seo',    title:'🔍 SEO' },
  ],
  fields: [
    // SERIES META
    { name:'seriesId',       title:'Series ID (internal)', type:'string', group:'meta', initialValue:'atlas-of-the-unspoken', readOnly:true },
    { name:'seriesTitle_en', title:'Series Title (EN)', type:'string', group:'meta', initialValue:'Atlas of the Unspoken', validation: R => R.required() },
    { name:'seriesTitle_fr', title:'Titre de la série (FR)', type:'string', group:'meta', initialValue:"Atlas de l'Inexprimé", validation: R => R.required() },
    { name:'seriesTitle_es', title:'Título de la serie (ES)', type:'string', group:'meta', initialValue:'El Atlas de lo No Dicho' },
    { name:'author',         title:'Author', type:'string', group:'meta', initialValue:'Jems S. Pompee', validation: R => R.required() },
    { name:'genre_en', title:'Genre (EN)', type:'string', group:'meta', initialValue:'Poetry / Prose Poetry' },
    { name:'genre_fr', title:'Genre (FR)', type:'string', group:'meta', initialValue:'Poésie / Poésie en prose' },
    { name:'genre_es', title:'Genre (ES)', type:'string', group:'meta', initialValue:'Poesía / Poesía en prosa' },
    { name:'languages', title:'Available Language Editions', type:'array', group:'meta', of:[{type:'string'}],
      options:{ list:['EN','FR','ES'] }, initialValue:['EN','FR'] },
    { name:'totalPoems', title:'Total Poems in Series', type:'number', group:'meta', initialValue:84 },
    { name:'seriesTagline_en', title:'Series Tagline (EN)', type:'string', group:'meta', initialValue:'Every silence keeps a geography of its own.' },
    { name:'seriesTagline_fr', title:'Tagline de la série (FR)', type:'string', group:'meta', initialValue:"Toute chose inexprimée garde sa propre géographie." },
    { name:'seriesTagline_es', title:'Tagline de la serie (ES)', type:'string', group:'meta', initialValue:'Todo silencio guarda su propia geografía.' },
    { name:'seriesOverview_en', title:'Series Overview (EN)', type:'text', group:'meta', rows:4 },
    { name:'seriesOverview_fr', title:'Présentation de la série (FR)', type:'text', group:'meta', rows:4 },
    { name:'seriesOverview_es', title:'Presentación de la serie (ES)', type:'text', group:'meta', rows:4 },
    // TOME I
    { name:'tome1_subtitle_en', title:'Tome I — Subtitle (EN)', type:'string', group:'tome1', initialValue:'The Inner Atlas' },
    { name:'tome1_subtitle_fr', title:'Tome I — Sous-titre (FR)', type:'string', group:'tome1', initialValue:"L'Atlas intérieur" },
    { name:'tome1_subtitle_es', title:'Tome I — Subtítulo (ES)', type:'string', group:'tome1', initialValue:'El Atlas Interior' },
    { name:'tome1_synopsis_en', title:'Tome I — Synopsis (EN)', type:'text', group:'tome1', rows:5 },
    { name:'tome1_synopsis_fr', title:'Tome I — Synopsis (FR)', type:'text', group:'tome1', rows:5 },
    { name:'tome1_synopsis_es', title:'Tome I — Sinopsis (ES)', type:'text', group:'tome1', rows:5 },
    { name:'tome1_poemCount', title:'Tome I — Number of Poems', type:'number', group:'tome1', initialValue:39 },
    { name:'tome1_cover_en', title:'Tome I — Cover Image (EN edition)', type:'image', group:'tome1', options:{ hotspot:true } },
    { name:'tome1_cover_fr', title:'Tome I — Cover Image (FR edition)', type:'image', group:'tome1', options:{ hotspot:true } },
    { name:'tome1_isbn_en_print', title:'Tome I — ISBN (EN Print)', type:'string', group:'tome1' },
    { name:'tome1_isbn_fr_print', title:'Tome I — ISBN (FR Print)', type:'string', group:'tome1' },
    { name:'tome1_isbn_ebook',    title:'Tome I — ISBN (eBook)',   type:'string', group:'tome1' },
    { name:'tome1_price',       title:'Tome I — Price (USD)', type:'number', group:'tome1' },
    { name:'tome1_isAvailable', title:'Tome I — Available for purchase', type:'boolean', group:'tome1', initialValue:true },
    // TOME II
    { name:'tome2_subtitle_en', title:'Tome II — Subtitle (EN)', type:'string', group:'tome2', initialValue:'The Outer Atlas' },
    { name:'tome2_subtitle_fr', title:'Tome II — Sous-titre (FR)', type:'string', group:'tome2', initialValue:"L'Atlas extérieur" },
    { name:'tome2_subtitle_es', title:'Tome II — Subtítulo (ES)', type:'string', group:'tome2', initialValue:'El Atlas Exterior' },
    { name:'tome2_synopsis_en', title:'Tome II — Synopsis (EN)', type:'text', group:'tome2', rows:5 },
    { name:'tome2_synopsis_fr', title:'Tome II — Synopsis (FR)', type:'text', group:'tome2', rows:5 },
    { name:'tome2_synopsis_es', title:'Tome II — Sinopsis (ES)', type:'text', group:'tome2', rows:5 },
    { name:'tome2_poemCount', title:'Tome II — Number of Poems', type:'number', group:'tome2', initialValue:45 },
    { name:'tome2_cover_en', title:'Tome II — Cover Image (EN edition)', type:'image', group:'tome2', options:{ hotspot:true } },
    { name:'tome2_cover_fr', title:'Tome II — Cover Image (FR edition)', type:'image', group:'tome2', options:{ hotspot:true } },
    { name:'tome2_isbn_en_print', title:'Tome II — ISBN (EN Print)', type:'string', group:'tome2' },
    { name:'tome2_isbn_fr_print', title:'Tome II — ISBN (FR Print)', type:'string', group:'tome2' },
    { name:'tome2_isbn_ebook',    title:'Tome II — ISBN (eBook)',   type:'string', group:'tome2' },
    { name:'tome2_price',       title:'Tome II — Price (USD)', type:'number', group:'tome2' },
    { name:'tome2_isAvailable', title:'Tome II — Available for purchase', type:'boolean', group:'tome2', initialValue:true },
    // RETAIL
    { name:'tome1_link_amazon',   title:'Tome I — Amazon link',    type:'url', group:'retail' },
    { name:'tome1_link_bookbaby', title:'Tome I — BookBaby link',  type:'url', group:'retail' },
    { name:'tome1_link_etsy',     title:'Tome I — Etsy link',      type:'url', group:'retail' },
    { name:'tome2_link_amazon',   title:'Tome II — Amazon link',   type:'url', group:'retail' },
    { name:'tome2_link_bookbaby', title:'Tome II — BookBaby link', type:'url', group:'retail' },
    { name:'tome2_link_etsy',     title:'Tome II — Etsy link',     type:'url', group:'retail' },
    { name:'bundle_link',  title:'Bundle Link (both tomes)', type:'url', group:'retail' },
    { name:'bundle_price', title:'Bundle Price (USD)',        type:'number', group:'retail' },
    // SEO
    { name:'seo_title_en', title:'Meta Title (EN)', type:'string', group:'seo', validation: R => R.max(60) },
    { name:'seo_desc_en',  title:'Meta Description (EN)', type:'text', group:'seo', rows:2, validation: R => R.max(155) },
    { name:'seo_title_fr', title:'Meta Title (FR)', type:'string', group:'seo', validation: R => R.max(60) },
    { name:'seo_desc_fr',  title:'Meta Description (FR)', type:'text', group:'seo', rows:2, validation: R => R.max(155) },
    { name:'seo_og_image', title:'OpenGraph Image', type:'image', group:'seo' },
  ],
  preview: {
    select: { title:'seriesTitle_en', subtitle:'author' },
    prepare: ({ title, subtitle }) => ({ title: title || 'Atlas Series', subtitle: `${subtitle} · 2 Tomes · EN + FR` }),
  },
};
